version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB:   ${PG_DATABASE}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      PG_HOST:     db
      PG_PORT:     ${PG_PORT}
      PG_USER:     ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DATABASE: ${PG_DATABASE}
      JWT_SECRET:  ${JWT_SECRET}
    working_dir: /usr/src/app
    volumes:
      - ./server:/usr/src/app        # hot‑reload in dev
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - server

volumes:
  db-data:
